import { Component } from '@angular/core';
import { ColumnDefinitionV1 } from 'src/app/shared/models/model';
import { Product } from '../product.model';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css'],
})
export class ProductComponent {
  productColumns: ColumnDefinitionV1<Product>[] = [
    { displayName: 'ID', fieldName: 'id', type: 'number' },
    { displayName: 'Name', fieldName: 'name', type: 'string' },
    { displayName: 'Category', fieldName: 'category', type: 'string' },
    { displayName: 'Price', fieldName: 'price', type: 'string' },
    { displayName: 'Stock', fieldName: 'stock', type: 'string' },
    { displayName: 'Supplier', fieldName: 'supplier', type: 'string' },
    { displayName: 'SKU', fieldName: 'sku', type: 'string' },
    { displayName: 'Launch Date', fieldName: 'launchDate', type: 'date' },
    { displayName: 'Rating', fieldName: 'rating', type: 'string' },
  ];
  products: Product[] = [
    {
      id: 1,
      name: 'Laptop Pro 15',
      category: 'Electronics',
      price: 1500,
      stock: 12,
      supplier: 'TechCorp',
      sku: 'LTP-001',
      launchDate: '2023-01-15',
      rating: 4.5,
    },
    {
      id: 2,
      name: 'Wireless Mouse',
      category: 'Accessories',
      price: 25,
      stock: 150,
      supplier: 'GadgetWorld',
      sku: 'MS-002',
      launchDate: '2022-11-05',
      rating: 4.2,
    },
    {
      id: 3,
      name: 'Office Chair',
      category: 'Furniture',
      price: 200,
      stock: 45,
      supplier: 'FurniCo',
      sku: 'CH-003',
      launchDate: '2022-06-20',
      rating: 4.0,
    },
    {
      id: 4,
      name: 'Gaming Keyboard',
      category: 'Accessories',
      price: 75,
      stock: 60,
      supplier: 'GadgetWorld',
      sku: 'KB-004',
      launchDate: '2023-02-12',
      rating: 4.6,
    },
    {
      id: 5,
      name: 'Smartphone X',
      category: 'Electronics',
      price: 999,
      stock: 30,
      supplier: 'TechCorp',
      sku: 'SPX-005',
      launchDate: '2023-03-01',
      rating: 4.8,
    },
    {
      id: 6,
      name: 'Desk Lamp',
      category: 'Furniture',
      price: 40,
      stock: 80,
      supplier: 'FurniCo',
      sku: 'DL-006',
      launchDate: '2022-09-15',
      rating: 4.1,
    },
    {
      id: 7,
      name: 'Bluetooth Headphones',
      category: 'Electronics',
      price: 120,
      stock: 50,
      supplier: 'SoundMaster',
      sku: 'BH-007',
      launchDate: '2023-01-25',
      rating: 4.4,
    },
    {
      id: 8,
      name: 'Water Bottle',
      category: 'Accessories',
      price: 15,
      stock: 200,
      supplier: 'DailyEssentials',
      sku: 'WB-008',
      launchDate: '2022-12-10',
      rating: 4.0,
    },
    {
      id: 9,
      name: 'Monitor 27"',
      category: 'Electronics',
      price: 300,
      stock: 25,
      supplier: 'TechCorp',
      sku: 'MON-009',
      launchDate: '2022-08-05',
      rating: 4.5,
    },
  ];
}
